language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=">=1.4,<1.5"
  - DJANGO_VERSION=">=1.5,<1.6"
install:
  - pip install Django$DJANGO_VERSION
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script:
  - coverage run ./runtests.py --with-xunit
after_success:
  - coveralls
